spring:
  config:
    import:
      - classpath:application-common.yml
  application:
    name: ozon-service
  datasource:
    url: jdbc:postgresql://localhost:5433/product_visor?options=-c%20TimeZone=Europe/Moscow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ozon
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    schemas: ozon
    default-schema: ozon

ozon:
  default-warehouse-id: 1020005000189785
  base-url: ${OZON_BASE_URL:https://api-seller.ozon.ru}
  client-id: ${OZON_CLIENT_ID:20}
  api-key: ${OZON_API_KEY:9b2c7f15a7}

# Настройка часового пояса для приложения
server:
  port: 9097
  servlet:
    encoding:
      charset: UTF-8
      force: true

# gRPC клиент конфигурация
grpc:
  client:
    order-service:
      address: localhost:9098
    product-service:
      address: localhost:9093

# Конфигурация автоматической синхронизации
app:
  sync:
    enabled: true
    checkpoint-name: FBO_ORDERS
    max-gap-minutes: 1 # Максимальный разрыв в минутах для автоматической синхронизации

# Идентификатор текущего маркета
application:
  market:
    name: OZON

# Kafka topics
kafka:
  topics:
    stock-events: stock-events

# Старая конфигурация для обратной совместимости
ozon-sync:
  enabled: true
  window-minutes: 1
  page-size: 100
  fixed-delay-ms: 120000

logging:
  level:
    ru.dmitartur.ozon.service.SyncService: INFO
    ru.dmitartur.ozon.service.OzonOrderSyncService: DEBUG

# Настройки безопасности наследуются из application-common.yml


