spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/product_visor?options=-c%20TimeZone=Europe/Moscow
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka:9092

grpc:
  client:
    order-service:
      address: order-service:9098
    product-service:
      address: product-visor-backend:9093

server:
  port: 9097

oauth2:
  client:
    token-uri: http://authorization-service:9099/oauth2/token


