spring:
  config:
    import:
      - classpath:application-common.yml
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    resources:
      static-locations: F:\images
  datasource:
    url: jdbc:postgresql://localhost:5433/product_visor
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: visor
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
  profiles:
    active: common
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.hbm2ddl: DEBUG
    ru.dmitartur.kafka: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
    ru.dmitartur.config.KafkaConfig: DEBUG
    ru.dmitartur.grpc.ProductGrpcServer: DEBUG
    net.devh.boot.grpc: DEBUG

# Kafka конфигурация (наследуется из common-core)
kafka:
  enabled: true
  topics:
    order-events: order-events

server:
  port: 8085

# gRPC конфигурация
grpc:
  server:
    port: 9093

file:
  upload-dir: F:\images