spring:
  config:
    import:
      - classpath:application-common.yml
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    resources:
      static-locations: F:\images
  datasource:
    url: jdbc:postgresql://localhost:5433/product_visor?options=-c%20TimeZone=Europe/Moscow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: visor
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: visor
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: visor
    default-schema: visor
    ignore-migration-patterns: "*:ignored"
  profiles:
    active: common
logging:
  level:
    root: INFO
    ru.dmitartur: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.hbm2ddl: INFO
    ru.dmitartur.kafka: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
    ru.dmitartur.config.KafkaConfig: INFO
    ru.dmitartur.grpc.ProductGrpcServer: INFO
    net.devh.boot.grpc: INFO

# Kafka конфигурация (наследуется из common-core)
kafka:
  enabled: true
  topics:
    order-events: order-events
    stock-events: stock-events

server:
  port: 8085

# gRPC конфигурация
grpc:
  server:
    port: 9093

file:
  upload-dir: F:\images