spring:
  web:
    resources:
      static-locations: F:\images
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 1545
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: visor
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        jdbc:
          time_zone: UTC
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
server:
  port: 8085

file:
  upload-dir: F:\images 