spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/product_visor
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    default-schema: orders
  flyway:
    locations: classpath:db/migration
    schemas: orders
    default-schema: orders
  profiles:
    active: common

# Специфичные для OrderService настройки (если нужны переопределения)
# kafka:
#   topics:
#     order-events: order-service-events

# gRPC конфигурация
grpc:
  server:
    port: 9098
  client:
    product-service:
      address: localhost:9093

# Специфичные для OrderService настройки логирования
logging:
  level:
    ru.dmitartur.order: DEBUG
    ru.dmitartur.order.service.ProductGrpcService: DEBUG
    net.devh.boot.grpc: DEBUG

# Порт приложения
server:
  port: 9088

# Конфигурация внешних сервисов
app:
  product-service:
    url: http://localhost:8085
